### ISSUE TITLE
Python CLI with jsonargparse

### ISSUE THREAD

**Issue by BerndDoser** [HITS-AIN/HiPSter#13]
Include a Python CLI using [jsonargparse](https://jsonargparse.readthedocs.io/en/latest/), which is also used in the Lightning CLI.

Example for a YAML config file:
```
url: https://space.h-its.org
title: gaia
output_folder: /var/www/html/space
max_order: 4
hips:
  decoder:
    model_path: models/gaia-calibrated-v2/decoder.onnx
  image_maker:
    class_path: hipster.SpectrumPlotter
    init_args:
      wavelengths:
        start: 336
        stop: 1021
        step: 2
      flip: True
```
